project:
  type: website
  output-dir: docs

website:
  title: "Mariarosaria Di Bagno"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: Projects.qmd 
        text: Projects
      - href: Work.qmd
        text: Work

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual













