project:
  type: website
  output-dir: docs

website:
  title: "Mariarosaria Di Bagno"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd 
      - Projects.qmd
      - Work.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual 













