project:
  type: website
  output-dir: docs

website:
  title: "mariarosaria.dibagno.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd

format:
  html:
    theme: cosmo
    css: styles-m.css
    toc: true

editor: visual

